project:
  type: website

website:
  title: DigiHistCH24
  favicon: logo.png
  open-graph: true
  twitter-card: true
  site-url: https://digihistch24.github.io/book-of-abstracts/
  repo-url: https://github.com/digihistch24/book-of-abstracts/
  issue-url: https://github.com/digihistch24/book-of-abstracts/issues/new/choose
  repo-actions: [edit, issue]
  page-navigation: true
  bread-crumbs: false
  back-to-top-navigation: true
  search:
    show-item-context: true
    type: overlay
  navbar:
    background: '#a5d7d2'
    logo-alt: ''
    title: '***DigiHistCH24***'
    tools:
      - icon: github
        url: https://github.com/digihistch24/book-of-abstracts/
        target: _blank
    left:
      - text: Home
        href: index.qmd
      - text: Book of Abstracts
        href: book-of-abstracts.qmd
      - text: Conference Program
        href: conference-program.qmd
      - text: Call for Contributions
        href: call-for-contributions.qmd
      - text: About
        href: about.qmd

  sidebar:
    style: 'docked'
    collapse-level: 1
    contents:
      - text: Home
        href: index.qmd
      - section: Book of Abstracts
        href: book-of-abstracts.qmd
        contents:
          - auto: submissions/*/index.qmd
      - section: Conference Program
        href: conference-program.qmd
        contents:
          - text: Schedule
            href: conference-program/schedule.qmd
          - text: Keynote
            href: submissions/keynote/index.qmd
          - text: Practical Information
            href: conference-program/practical-information.qmd
          - text: Event Digital History Network
            href: conference-program/info-event-digital-history-network-switzerland.qmd
          - text: Event SSH ORD
            href: conference-program/info-event-ssh-ord.qmd
      - section: Call for Contributions
        href: call-for-contributions.qmd
        contents:
          - auto: call-for-contributions/*.qmd
      - section: About
        href: about.qmd
        contents:
          - auto: about/*.qmd

format:
  html:
    link-external-icon: true
    link-external-newwindow: true
    toc: true
    theme:
      light: [cosmo, styles.css]
      dark: [darkly, theme-dark.css]
    code-block-border-left: '#a5d7d2'
    code-block-bg: true
    code-copy: true
    code-fold: true
    code-tools: true
    code-overflow: wrap
    include-in-header:
      - custom-header.html
    license: CC BY-SA 4.0
    page-layout: full
    mainfont: Jost
    html-math-method: plain

freeze: false

editor: visual
