project:
  type: website

website:
  title: book-of-abstracts
  favicon: android-chrome-512x512.png
  open-graph: true
  twitter-card: true
  site-url: https://digihistch24.github.io/book-of-abstracts/
  repo-url: https://github.com/digihistch24/book-of-abstracts/
  issue-url: https://github.com/digihistch24/book-of-abstracts/issues/new/choose
  repo-actions: [edit, issue]
  page-navigation: true
  bread-crumbs: true
  back-to-top-navigation: true
  search:
    show-item-context: true
    type: overlay
  navbar:
    logo: android-chrome-512x512.png
    logo-alt: ''
    title: book-of-abstracts
    tools:
      - icon: github
        url: https://github.com/digihistch24/book-of-abstracts/
    left:
      - text: Abstracts
        href: book-of-abstracts.md
      - text: About
        href: index.qmd

  sidebar:
    contents:
      - section: Abstracts
        href: book-of-abstracts.md
        contents:
          - text: Submission Template
            href: submission/index.qmd
      - section: About
        href: index.qmd
        contents:
          - text: Changelog
            href: CHANGELOG.md
          - text: Code of Conduct
            href: CODE_OF_CONDUCT.md
          - text: Contributing
            href: CONTRIBUTING.md
          - text: License (Data)
            href: LICENSE-CCBYSA.md
          - text: License (Code)
            href: LICENSE-AGPL.md
          - text: Security
            href: SECURITY.md

format:
  html:
    toc: true
    theme: cosmo
    code-copy: true
    code-overflow: wrap
    css: styles.css

freeze: true

editor: visual
