project:
  type: website

website:
  title: DigiHistCH24 Book of Abstracts
  favicon: logo.png
  open-graph: true
  twitter-card: true
  site-url: https://digihistch24.github.io/book-of-abstracts/
  repo-url: https://github.com/digihistch24/book-of-abstracts/
  issue-url: https://github.com/digihistch24/book-of-abstracts/issues/new/choose
  repo-actions: [edit, issue]
  page-navigation: true
  bread-crumbs: true
  back-to-top-navigation: true
  search:
    show-item-context: true
    type: overlay
  navbar:
    background: '#a5d7d2'
    logo-alt: ''
    title: '***DigiHistCH24*** Book of Abstracts'
    tools:
      - icon: github
        url: https://github.com/digihistch24/book-of-abstracts/
    left:
      - text: Abstracts
        href: index.qmd
      - text: Conference Program
        href: https://conferences.unibas.ch/frontend/index.php?page_id=1882
      - text: Registration
        href: https://conferences.unibas.ch/frontend/index.php?page_id=1424&booking_registration_action=show&booking_registration_controller=offer
      - text: Call for Contributions
        href: https://conferences.unibas.ch/frontend/index.php?folder_id=234&page_id=
      - text: About
        href: about.qmd

  sidebar:
    style: 'docked'
    contents:
      - section: Abstracts
        href: index.qmd
        contents:
          - auto: submissions/*/index.qmd
      - section: About
        href: about.qmd
        contents:
          - text: Changelog
            href: CHANGELOG.md
          - text: Code of Conduct
            href: CODE_OF_CONDUCT.md
          - text: Contributing
            href: CONTRIBUTING.md
          - text: License (Data)
            href: LICENSE-CCBYSA.md
          - text: License (Code)
            href: LICENSE-AGPL.md
          - text: Security
            href: SECURITY.md

format:
  html:
    link-external-icon: true
    link-external-newwindow: true
    toc: true
    theme: cosmo
    code-copy: true
    code-overflow: wrap
    css: styles.css
    include-in-header:
      - custom-header.html
    license: CC BY-SA 4.0
    page-layout: full

freeze: false

editor: visual
